site_name: datakb
site_url: https://mydomain.org/
repo_name: dyvenia/data-excellence
repo_url: https://github.com/dyvenia/data-excellence
nav:
  - Home: index.md
  - Marts: 
    - Executive Overview: marts/overview.md
    - Methodology: marts/methodology.md
    - Operating Models: marts/op_models.md
    - Roles: marts/roles.md
  - Organizzation: 
    - Executive Overview: organizzation/overview.md
    - Methodology: organizzation/methodology.md
    - Operating Models: organizzation/op_models.md
    - Roles: organizzation/roles.md
  - Data Governance: 
    - Executive Overview: data_governance/overview.md
    - Methodology: data_governance/methodology.md
    - Operating Models: data_governance/op_model.md
    - Roles: data_governance/roles.md
  - Data Platform: 
    - Executive Overview: data_platform/overview.md
    - Methodology:
      - Methodology Overview: data_platform/methodology_overview.md
      - Infrastructure as Code (IaC): data_platform/iac.md
      - CI/CD: data_platform/cicd.md
      - Orchestration: data_platform/orchestration.md
      - Integrations: data_platform/integrations.md
    - Ingestion: data_platform/ingestion.md
    - Roles: data_platform/roles.md
theme:
  name: material
  palette:
    primary: deep purple
  features:
    - navigation.path
    - navigation.tabs
    - navigation.expand
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format